branches:
  only:
    - master

language: cpp

install:
  - cmake --version

  - git clone --branch=4.2.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"
  - git clone --branch=4.3.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"
  - git clone --branch=5.0.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"
  - git clone --branch=5.2.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.0"

script-anchors:
  - &script-Makefiles
    # Configure and build Reprojucer.cmake helpers and Jucer2Reprojucer with JUCE 4.2.0
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_4.2.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0/modules"
    - cmake --build .
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_4.2.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0/modules"

    # Configure and build Reprojucer.cmake helpers and Jucer2Reprojucer with JUCE 4.3.1
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_4.3.1_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1/modules"
    - cmake --build .
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_4.3.1_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1/modules"

    # Configure and build Reprojucer.cmake helpers and Jucer2Reprojucer with JUCE 5.0.0
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_5.0.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0/modules"
    - cmake --build .
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_5.0.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0/modules"

    # Configure and build Reprojucer.cmake helpers and Jucer2Reprojucer with JUCE 5.2.0
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_5.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_5.2.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.0"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.0/modules"
    - cmake --build .
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_5.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_5.2.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.0"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.0/modules"

    # Check that generated CMakeLists.txt files are up-to-date
    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/Debug_4.2.0_build/Jucer2Reprojucer/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="generated/JUCE-4.2.0"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/Debug_4.3.1_build/Jucer2Reprojucer/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="generated/JUCE-4.3.1"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/Debug_5.0.0_build/Jucer2Reprojucer/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="generated/JUCE-5.0.0"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.0"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/Debug_5.2.0_build/Jucer2Reprojucer/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="generated/JUCE-5.2.0"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    # Configure all JUCE 4.2.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_4.2.0_build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="4.2.0"
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_4.2.0_build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="4.2.0"

    # Configure all JUCE 4.3.1 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_4.3.1_build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="4.3.1"
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_4.3.1_build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="4.3.1"

    # Configure all JUCE 5.0.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_5.0.0_build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="5.0.0"
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_5.0.0_build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="5.0.0"

    # Configure all JUCE 5.2.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_5.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_5.2.0_build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="5.2.0"
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_5.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_5.2.0_build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="5.2.0"

  - &script-Xcode
    # Configure and build Reprojucer.cmake helpers and Jucer2Reprojucer with JUCE 4.2.0
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/4.2.0_build
    - >
      cmake .. -G Xcode
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0/modules"
    - cmake --build . --config Debug

    # Configure and build Reprojucer.cmake helpers and Jucer2Reprojucer with JUCE 4.3.1
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/4.3.1_build
    - >
      cmake .. -G Xcode
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1/modules"
    - cmake --build . --config Debug

    # Configure and build Reprojucer.cmake helpers and Jucer2Reprojucer with JUCE 5.0.0
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/5.0.0_build
    - >
      cmake .. -G Xcode
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0/modules"
    - cmake --build . --config Debug

    # Configure and build Reprojucer.cmake helpers and Jucer2Reprojucer with JUCE 5.2.0
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/5.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/5.2.0_build
    - >
      cmake .. -G Xcode
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.0"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.0/modules"
    - cmake --build . --config Debug

    # Check that generated CMakeLists.txt files are up-to-date
    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/4.2.0_build/Jucer2Reprojucer/Debug/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="generated/JUCE-4.2.0"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/4.3.1_build/Jucer2Reprojucer/Debug/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="generated/JUCE-4.3.1"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/5.0.0_build/Jucer2Reprojucer/Debug/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="generated/JUCE-5.0.0"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.0"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/5.2.0_build/Jucer2Reprojucer/Debug/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="generated/JUCE-5.2.0"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    # Configure all JUCE 4.2.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/4.2.0_build
    - cmake .. -G Xcode -DJUCE_VERSION="4.2.0"

    # Configure all JUCE 4.3.1 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/4.3.1_build
    - cmake .. -G Xcode -DJUCE_VERSION="4.3.1"

    # Configure all JUCE 5.0.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/5.0.0_build
    - cmake .. -G Xcode -DJUCE_VERSION="5.0.0"

    # Configure all JUCE 5.2.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/5.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/5.2.0_build
    - cmake .. -G Xcode -DJUCE_VERSION="5.2.0"

matrix:
  include:
    - os: linux
      services:
        - docker
      before_install:
        - docker build --tag mcmartin/frut - < ci/ubuntu-xenial.dockerfile
        - |
          function cmake {
            docker run --rm -v "${TRAVIS_BUILD_DIR}":"${TRAVIS_BUILD_DIR}" -w "$PWD" mcmartin/frut /usr/bin/cmake $@
          }
      script: *script-Makefiles

    - os: osx
      env: GENERATOR=Makefiles
      script: *script-Makefiles

    - os: osx
      env: GENERATOR=Xcode
      script: *script-Xcode
